services:
  - type: web
    name: stami-chat
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"  # Change this if your main file is named differently
    envVars:
      SECRET: "your_secret_key"  # Replace with your actual secret key
